# ---
# # playbook
# - hosts: webserver
#   become: yes
#   gather_facts: no

#   tasks:

#     - name: Pull latest image
#       shell: docker pull vikas7974344880/stream-webinterface:latest

#     - name: Stop existing container
#       shell: docker stop stream-webinterface || true

#     - name: Remove existing container
#       shell: docker rm stream-webinterface || true

#     - name: Run container
#       shell: |
#         docker run -d \
#         --name stream-webinterface \
#         -p 8501:8501 \
#         --restart unless-stopped \
#         vikas7974344880/stream-webinterface:latest


---
- hosts: webserver
  become: yes

  tasks:

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest image
      shell: docker pull vikas7974344880/stream-webinterface:latest

    - name: Stop existing container
      shell: docker stop stream-webinterface || true

    - name: Remove existing container
      shell: docker rm stream-webinterface || true

    - name: Run container
      shell: |
        docker run -d \
        --name stream-webinterface \
        -p 8501:8501 \
        --restart unless-stopped \
        vikas7974344880/stream-webinterface:latest