---
- hosts: webserver
  become: yes

  tasks:

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes